export interface Avatar {
  id: string;
  emoji: string;
  label: string;
  category: string;
}

export const AVATAR_CATEGORIES = [
  "NFL Teams",
  "Football",
  "Trophy Room",
  "Animals",
  "Weather",
  "Food & Grind",
  "Space",
  "Tech",
] as const;

export const AVATARS: Avatar[] = [
  { id: "nfl_buf", emoji: "🦬", label: "Bills Mafia", category: "NFL Teams" },
  { id: "nfl_mia", emoji: "🐬", label: "Fins Up", category: "NFL Teams" },
  { id: "nfl_ne",  emoji: "⚓", label: "Patriot Way", category: "NFL Teams" },
  { id: "nfl_nyj", emoji: "✈️", label: "Gang Green", category: "NFL Teams" },
  { id: "nfl_bal", emoji: "🦅", label: "Raven Nation", category: "NFL Teams" },
  { id: "nfl_cin", emoji: "🐯", label: "Who Dey", category: "NFL Teams" },
  { id: "nfl_cle", emoji: "🐕", label: "Dawg Pound", category: "NFL Teams" },
  { id: "nfl_pit", emoji: "⚙️", label: "Steeler Nation", category: "NFL Teams" },
  { id: "nfl_hou", emoji: "🤠", label: "Texans Pride", category: "NFL Teams" },
  { id: "nfl_ind", emoji: "🐴", label: "Colts Country", category: "NFL Teams" },
  { id: "nfl_jax", emoji: "🐆", label: "Duval", category: "NFL Teams" },
  { id: "nfl_ten", emoji: "⚡", label: "Titan Up", category: "NFL Teams" },
  { id: "nfl_den", emoji: "🐎", label: "Mile High", category: "NFL Teams" },
  { id: "nfl_kc",  emoji: "🏹", label: "Kingdom", category: "NFL Teams" },
  { id: "nfl_lv",  emoji: "☠️", label: "Raider Nation", category: "NFL Teams" },
  { id: "nfl_lac", emoji: "⚡", label: "Bolt Up", category: "NFL Teams" },
  { id: "nfl_dal", emoji: "⭐", label: "Cowboys Nation", category: "NFL Teams" },
  { id: "nfl_nyg", emoji: "🗽", label: "Big Blue", category: "NFL Teams" },
  { id: "nfl_phi", emoji: "🦅", label: "Fly Eagles Fly", category: "NFL Teams" },
  { id: "nfl_was", emoji: "🪖", label: "HTTR", category: "NFL Teams" },
  { id: "nfl_chi", emoji: "🐻", label: "Bear Down", category: "NFL Teams" },
  { id: "nfl_det", emoji: "🦁", label: "Detroit Lions", category: "NFL Teams" },
  { id: "nfl_gb",  emoji: "🧀", label: "Cheeseheads", category: "NFL Teams" },
  { id: "nfl_min", emoji: "🏈", label: "Skol Vikings", category: "NFL Teams" },
  { id: "nfl_atl", emoji: "🦅", label: "Rise Up", category: "NFL Teams" },
  { id: "nfl_car", emoji: "🐱", label: "Keep Pounding", category: "NFL Teams" },
  { id: "nfl_no",  emoji: "⚜️", label: "Who Dat", category: "NFL Teams" },
  { id: "nfl_tb",  emoji: "🏴‍☠️", label: "Pewter Pirates", category: "NFL Teams" },
  { id: "nfl_ari", emoji: "🔴", label: "Cardinals Pride", category: "NFL Teams" },
  { id: "nfl_lar", emoji: "🐏", label: "Rams House", category: "NFL Teams" },
  { id: "nfl_sf",  emoji: "🌉", label: "Faithful", category: "NFL Teams" },
  { id: "nfl_sea", emoji: "🦅", label: "12s", category: "NFL Teams" },
  { id: "fb_ball",    emoji: "🏈", label: "The Ball",       category: "Football" },
  { id: "fb_helmet",  emoji: "⛑️", label: "Helmet",         category: "Football" },
  { id: "fb_coach",   emoji: "📋", label: "Head Coach",     category: "Football" },
  { id: "fb_ref",     emoji: "🟡", label: "Flag on Play",   category: "Football" },
  { id: "fb_td",      emoji: "🙌", label: "Touchdown",      category: "Football" },
  { id: "fb_rush",    emoji: "💨", label: "Speed Demon",    category: "Football" },
  { id: "fb_blitz",   emoji: "🔥", label: "Blitz Package",  category: "Football" },
  { id: "fb_punt",    emoji: "🦵", label: "Punt King",      category: "Football" },
  { id: "fb_snap",    emoji: "🤜", label: "Snap Count",     category: "Football" },
  { id: "fb_fumble",  emoji: "😱", label: "Fumble!",        category: "Football" },
  { id: "fb_pick",    emoji: "🎯", label: "Pick Six",       category: "Football" },
  { id: "fb_hike",    emoji: "📣", label: "Hike!",          category: "Football" },
  { id: "tr_gold",    emoji: "🏆", label: "Champion",       category: "Trophy Room" },
  { id: "tr_silver",  emoji: "🥈", label: "Runner-Up",      category: "Trophy Room" },
  { id: "tr_bronze",  emoji: "🥉", label: "Third Place",    category: "Trophy Room" },
  { id: "tr_crown",   emoji: "👑", label: "The Crown",      category: "Trophy Room" },
  { id: "tr_goat",    emoji: "🐐", label: "G.O.A.T.",       category: "Trophy Room" },
  { id: "tr_medal",   emoji: "🎖️", label: "Decorated",      category: "Trophy Room" },
  { id: "tr_ring",    emoji: "💍", label: "Ring Bearer",    category: "Trophy Room" },
  { id: "tr_legend",  emoji: "⚡", label: "Legend",         category: "Trophy Room" },
  { id: "an_bull",    emoji: "🐂", label: "Bulldozer",      category: "Animals" },
  { id: "an_wolf",    emoji: "🐺", label: "Lone Wolf",      category: "Animals" },
  { id: "an_shark",   emoji: "🦈", label: "Shark",          category: "Animals" },
  { id: "an_gorilla", emoji: "🦍", label: "Silverback",     category: "Animals" },
  { id: "an_lion",    emoji: "🦁", label: "Lion Heart",     category: "Animals" },
  { id: "an_bear",    emoji: "🐻", label: "Grizzly",        category: "Animals" },
  { id: "an_falcon",  emoji: "🦅", label: "Falcon",         category: "Animals" },
  { id: "an_snake",   emoji: "🐍", label: "Cold Blooded",   category: "Animals" },
  { id: "an_rhino",   emoji: "🦏", label: "Rhino",          category: "Animals" },
  { id: "an_panther", emoji: "🐈", label: "Black Panther",  category: "Animals" },
  { id: "wx_storm",   emoji: "⛈️", label: "Storm",          category: "Weather" },
  { id: "wx_blizzard",emoji: "❄️", label: "Blizzard",       category: "Weather" },
  { id: "wx_thunder", emoji: "🌩️", label: "Thunder",        category: "Weather" },
  { id: "wx_heat",    emoji: "🌡️", label: "Heat Wave",      category: "Weather" },
  { id: "wx_tornado", emoji: "🌪️", label: "Tornado",        category: "Weather" },
  { id: "wx_lightning",emoji: "⚡", label: "Lightning",     category: "Weather" },
  { id: "wx_sun",     emoji: "☀️", label: "Sunshine",       category: "Weather" },
  { id: "fg_steak",   emoji: "🥩", label: "Red Meat",       category: "Food & Grind" },
  { id: "fg_fire",    emoji: "🔥", label: "On Fire",        category: "Food & Grind" },
  { id: "fg_hustle",  emoji: "💼", label: "Grindset",       category: "Food & Grind" },
  { id: "fg_money",   emoji: "💰", label: "Money Moves",    category: "Food & Grind" },
  { id: "fg_ice",     emoji: "🧊", label: "Ice Cold",       category: "Food & Grind" },
  { id: "fg_rocket",  emoji: "🚀", label: "Rocket Ship",    category: "Food & Grind" },
  { id: "fg_diamond", emoji: "💎", label: "Diamond Hands",  category: "Food & Grind" },
  { id: "fg_coffee",  emoji: "☕", label: "Always Grinding", category: "Food & Grind" },
  { id: "sp_moon",    emoji: "🌙", label: "Moon Shot",      category: "Space" },
  { id: "sp_star",    emoji: "⭐", label: "Star Power",     category: "Space" },
  { id: "sp_alien",   emoji: "👽", label: "From Another Planet", category: "Space" },
  { id: "sp_comet",   emoji: "☄️", label: "Comet",          category: "Space" },
  { id: "sp_galaxy",  emoji: "🌌", label: "Galaxy Brain",   category: "Space" },
  { id: "sp_saturn",  emoji: "🪐", label: "Saturn",         category: "Space" },
  { id: "tc_robot",   emoji: "🤖", label: "The Algorithm",  category: "Tech" },
  { id: "tc_brain",   emoji: "🧠", label: "Big Brain",      category: "Tech" },
  { id: "tc_chart",   emoji: "📈", label: "Analytics",      category: "Tech" },
  { id: "tc_chip",    emoji: "💾", label: "Data Driven",    category: "Tech" },
  { id: "tc_target",  emoji: "🎯", label: "Precision",      category: "Tech" },
  { id: "tc_hack",    emoji: "⌨️", label: "Draft Hacker",   category: "Tech" },
];

export const DEFAULT_AVATAR_ID = "fb_ball";
